var datos = [
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "Chuquibamba", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "Granada", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "Quinjalca", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "San Francisco de Daguas", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "Soloco", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Chachapoyas", distrito: "Sonche", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Lamud", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Longuita", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Lonya Chico", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Luya Viejo", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Maria", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Luya", distrito: "Trita", estado: "Emergencia" },
    { departamento: "Amazonas", provincia: "Rodriguez de Mendoza", distrito: "Longar", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Carhuaz", distrito: "Anta", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Carhuaz", distrito: "Yungar", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Corongo", distrito: "Bambas", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Corongo", distrito: "La Pampa", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Huaraz", distrito: "Jangas", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Huaraz", distrito: "La Libertad", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Huaylas", distrito: "Santo Toribio", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Ocros", distrito: "Congas", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Yungay", distrito: "Ranrahirca", estado: "Emergencia" },
    { departamento: "Ancash", provincia: "Yungay", distrito: "Shupluy", estado: "Emergencia" },
    { departamento: "Apurimac", provincia: "Andahuaylas", distrito: "Andahuaylas", estado: "Emergencia" },
    { departamento: "Apurimac", provincia: "Andahuaylas", distrito: "Andarapa", estado: "Emergencia" },
    { departamento: "Apurimac", provincia: "Antabamba", distrito: "Antabamba", estado: "Emergencia" },
    { departamento: "Apurimac", provincia: "Chincheros", distrito: "Chincheros", estado: "Emergencia" },
    { departamento: "Apurimac", provincia: "Grau", distrito: "Chuquibambilla", estado: "Emergencia" },
    { departamento: "Ayacucho", provincia: "La Mar", distrito: "Ninabamba", estado: "Emergencia" },
    { departamento: "Ayacucho", provincia: "La Mar", distrito: "Patibamba", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajabamba", distrito: "Condebamba", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajabamba", distrito: "Sitacocha", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajamarca", distrito: "Encañada", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajamarca", distrito: "Jesus", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajamarca", distrito: "Llacanora", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajamarca", distrito: "Matara", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cajamarca", distrito: "Namora", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Celendin", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Chumuch", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Cortegana", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Huasmin", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Jorge Chavez", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Jose Galvez", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "La Libertad de Pallan", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Miguel Iglesias", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Oxamarca", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Sorochuco", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Sucre", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Celendin", distrito: "Utco", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Anguia", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Chadin", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Chalamarca", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Chiguirip", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Chimban", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Choropampa", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Chota", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Cochabamba", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Conchan", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Lajas", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Paccha", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Pion", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Chota", distrito: "Tacabamba", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Callayuc", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Choros", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Cujillo", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Cutervo", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "La Ramada", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Querocotillo", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "San Andres de Cutervo", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "San Juan de Cutervo", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "San Luis de Lucma", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Santa Cruz", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Santo Domingo de la Capilla", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Santo Tomas", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Socota", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Cutervo", distrito: "Toribio Casanova", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Hualgayoc", distrito: "Bambamarca", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Hualgayoc", distrito: "Hualgayoc", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Bellavista", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Chontali", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Huabal", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Jaen", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Las Pirias", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "Pomahuaca", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "San Felipe", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "Jaen", distrito: "San Jose del Alto", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Ignacio", distrito: "La Coipa", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Ignacio", distrito: "Tabaconas", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Chancay", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Eduardo Villanueva", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Gregorio Pita", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Ichocan", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Jose Manuel Quiroz", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Jose Sabogal", estado: "Emergencia" },
    { departamento: "Cajamarca", provincia: "San Marcos", distrito: "Pedro Galvez", estado: "Emergencia" },
    { departamento: "Huancavelica", provincia: "Churcampa", distrito: "Anco", estado: "Emergencia" },
    { departamento: "Ica", provincia: "Chincha", distrito: "Chavin", estado: "Emergencia" },
    { departamento: "Ica", provincia: "Ica", distrito: "Ica", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Bolivar", distrito: "Bolivar", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Bolivar", distrito: "Ucuncha", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Pataz", distrito: "Huancaspata", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Pataz", distrito: "Huayo", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Pataz", distrito: "Santiago de Challas", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Pataz", distrito: "Taurija", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Sanchez Carrion", distrito: "Marcabal", estado: "Emergencia" },
    { departamento: "La Libertad", provincia: "Trujillo", distrito: "Alto Trujillo", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Canta", distrito: "Arahuay", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Canta", distrito: "Huamantanga", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Cañete", distrito: "Imperial", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Cañete", distrito: "Lunahuana", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Cañete", distrito: "Quilmana", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Callahuanca", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Carampoma", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Huachupampa", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Huanza", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Huarochiri", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Langa", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "San Andres de Tupicocha", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "San Bartolome", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "San Mateo de Otao", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "San Pedro de Casta", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "San Pedro de Laraos", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Santa Cruz de Cocachacra", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Huarochiri", distrito: "Surco", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Lima", distrito: "Puente Piedra", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Oyon", distrito: "Cochamarca", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Oyon", distrito: "Pachangara", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Cacra", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Catahuasi", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Omas", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Quinches", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "San Pedro de Pilas", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Tauripampa", estado: "Emergencia" },
    { departamento: "Lima", provincia: "Yauyos", distrito: "Viñac", estado: "Emergencia" },
    { departamento: "Callao", provincia: "Callao", distrito: "Callao", estado: "Emergencia" },
    { departamento: "Callao", provincia: "Callao", distrito: "Carmen de la Legua Reynoso", estado: "Emergencia" },
    { departamento: "Callao", provincia: "Callao", distrito: "Ventanilla", estado: "Emergencia" },
    { departamento: "Pasco", provincia: "Pasco", distrito: "Chaupimarca", estado: "Emergencia" },
];



console.log(datos);